-- Truncates all tables owned by our team. Will not touch users, roles and other shared tables
-- In case of editing of this script note that the order of truncates MATTERS (due to FK constraints)

TRUNCATE TABLE NBPT3.NBP_NOTIFICATION CASCADE;
TRUNCATE TABLE NBPT3.NBP_ABSENCE_EXCUSE CASCADE;
TRUNCATE TABLE NBPT3.NBP_ATTENDANCE CASCADE;
TRUNCATE TABLE NBPT3.NBP_ENROLLMENT CASCADE;
TRUNCATE TABLE NBPT3.NBP_COURSE_SESSION CASCADE;
TRUNCATE TABLE NBPT3.NBP_TIMETABLE CASCADE;
TRUNCATE TABLE NBPT3.NBP_COURSE CASCADE;
TRUNCATE TABLE NBPT3.NBP_PROFESSOR CASCADE;
TRUNCATE TABLE NBPT3.NBP_STUDENT CASCADE;
TRUNCATE TABLE NBPT3.NBP_STUDY_PROGRAM CASCADE;
TRUNCATE TABLE NBPT3.NBP_ROOM CASCADE;
TRUNCATE TABLE NBPT3.NBP_DEPARTMENT CASCADE;
