services:
  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_DATA_MONGODB_URI: ${NBP_MONGODB_URI}
      SPRING_DATA_MONGODB_DATABASE: ${NBP_MONGODB_DATABASE}
    extra_hosts:
      - "host.docker.internal:host-gateway"