CREATE OR REPLACE PROCEDURE NBPT3.BACKUP_TABELE
AUTHID CURRENT_USER
AS
BEGIN
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE NBPT3.NBP_COURSE_BACKUP'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE NBPT3.NBP_PROFESSOR_BACKUP'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE NBPT3.NBP_STUDENT_BACKUP'; EXCEPTION WHEN OTHERS THEN NULL; END;

  EXECUTE IMMEDIATE 'CREATE TABLE NBPT3.NBP_COURSE_BACKUP AS SELECT * FROM NBPT3.NBP_COURSE';
  EXECUTE IMMEDIATE 'CREATE TABLE NBPT3.NBP_PROFESSOR_BACKUP AS SELECT * FROM NBPT3.NBP_PROFESSOR';
  EXECUTE IMMEDIATE 'CREATE TABLE NBPT3.NBP_STUDENT_BACKUP AS SELECT * FROM NBPT3.NBP_STUDENT';
END;
/