-- Creates the reports table which allows saving analytics reports.

CREATE TABLE NBP_REPORT (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TYPE VARCHAR(20) NOT NULL,
    CONTENT BLOB NOT NULL
);
